CAUCA-9-1-1/survip-webapi

- Survi.Prevention.DataLayer/ManagementContext.cs
- Survi.Prevention.Models/Buildings/Building.cs
- Survi.Prevention.Models/DataTransfertObjects/InterventionDetailForWeb.cs
- Survi.Prevention.Models/DataTransfertObjects/InterventionFormBuildingForList.cs
- Survi.Prevention.Models/DataTransfertObjects/InterventionFormFireHydrantForList.cs
- Survi.Prevention.Models/InspectionManagement/Inspection.cs
- Survi.Prevention.Models/InspectionManagement/InterventionForm.cs
- Survi.Prevention.ServiceLayer/Services/InterventionFormBuildingService.cs
- Survi.Prevention.ServiceLayer/Services/InterventionFormFireHydrantService.cs
- Survi.Prevention.WebApi/Controllers/InterventionFormBuildingController.cs
- Survi.Prevention.WebApi/Controllers/InterventionFormCourseController.cs
- Survi.Prevention.WebApi/Controllers/InterventionFormFireHydrantController.cs
- Survi.Prevention.WebApi/Startup.cs
All controllers needed for the inspection's readonly pages have been added.
> Inspection pages

- Survi.Prevention.DataLayer/ManagementContext.cs
- Survi.Prevention.DataLayer/Mapping/FireSafetyDepartmentCityServingMapping.cs
- Survi.Prevention.DataLayer/Mapping/FireSafetyDepartmentMapping.cs
- Survi.Prevention.Models/FireSafetyDepartments/City.cs
- Survi.Prevention.Models/FireSafetyDepartments/FireSafetyDepartment.cs
- Survi.Prevention.Models/FireSafetyDepartments/FireSafetyDepartmentServing.cs
- Survi.Prevention.ServiceLayer/Services/BuildingService.cs
- Survi.Prevention.ServiceLayer/Services/FireSafetyDepartmentService.cs
- Survi.Prevention.ServiceLayer/Services/FirestationService.cs
- Survi.Prevention.ServiceLayer/Services/WebuserService.cs
- Survi.Prevention.WebApi/Controllers/BuildingController.cs
- Survi.Prevention.WebApi/Controllers/FireSafetyDepartmentController.cs
- Survi.Prevention.WebApi/Controllers/FirestationController.cs
- Survi.Prevention.WebApi/Controllers/WebuserController.cs
- Survi.Prevention.WebApi/Startup.cs
Please validate only the section "firestation" and "firesafetydepartment"
> Management access

- Survi.Prevention.DataLayer/InitialData/InitialDataForBaseTable.cs
- Survi.Prevention.DataLayer/ManagementContext.cs
- Survi.Prevention.DataLayer/ManagementContextInitializer.cs
- Survi.Prevention.DataLayer/Mapping/BuildingAnomalyMapping.cs
- Survi.Prevention.DataLayer/Mapping/BuildingAnomalyPictureMapping.cs
- Survi.Prevention.DataLayer/Mapping/BuildingDetailMapping.cs
- Survi.Prevention.DataLayer/Mapping/ConstructionFireResistanceTypeLocalizationMapping.cs
- Survi.Prevention.DataLayer/Mapping/ConstructionFireResistanceTypeMapping.cs
- Survi.Prevention.DataLayer/Mapping/ConstructionTypeLocalizationMapping.cs
- Survi.Prevention.DataLayer/Mapping/UnitOfMeasureMapping.cs
- Survi.Prevention.Models/Buildings/Building.cs
- Survi.Prevention.Models/Buildings/BuildingAnomaly.cs
- Survi.Prevention.Models/Buildings/BuildingAnomalyPicture.cs
- Survi.Prevention.Models/Buildings/BuildingDetails.cs
- Survi.Prevention.Models/Buildings/BuildingHazardousMaterial.cs
- Survi.Prevention.Models/Buildings/BuildingSprinkler.cs
- Survi.Prevention.Models/Buildings/ConstructionFireResistanceType.cs
- Survi.Prevention.Models/Buildings/ConstructionFireResistanceTypeLocalization.cs
- Survi.Prevention.Models/FireHydrants/FireHydrant.cs
- Survi.Prevention.Models/FireHydrants/FireHydrantConnection.cs
- Survi.Prevention.Models/UnitOfMeasure.cs
- New anomalies tables.
- New FireResistanceType table.
- A lot of stuff added to the data seeding feature.
- UnitOfMeasure final design.
- Few fixes to models and mapping.
> Database refactoring

- Survi.Prevention.DataLayer/Mapping/FireHydrantMapping.cs
- Survi.Prevention.Models/DataTransfertObjects/InspectionBuildingDetailForWeb.cs
- Survi.Prevention.Models/InspectionManagement/Inspection.cs
- Survi.Prevention.ServiceLayer/Services/InspectionDetailService.cs
FireHydrant mapping fix (i know this has already been done in another branch, but I didn't want to wait for it).
Building.Detail is now optional.
Inspection.IdInterventionForm has been removed.
> Data layer fixes

- Survi.Prevention.DataLayer/ManagementContext.cs
- Survi.Prevention.Models/DataTransfertObjects/FireHydrantForList.cs
- Survi.Prevention.ServiceLayer/AddressGenerator.cs
- Survi.Prevention.ServiceLayer/AddressGeneratorWithDB.cs
- Survi.Prevention.ServiceLayer/Services/FireHydrantService.cs
- Survi.Prevention.ServiceLayer/Services/InspectionBuildingFireHydrantService.cs
- Survi.Prevention.WebApi/Controllers/FireHydrantController.cs
- Survi.Prevention.WebApi/Controllers/InspectionFireHydrantController.cs
Functions : 
- List of fire hydrant for target building
- List of city fire hydrant not linked to target buyilding
- Add new building fire hydrant
- Remove a building fire hydrant
> Management building fire hydrant

- Survi.Prevention.DataLayer/ManagementContext.cs
- Survi.Prevention.DataLayer/Mapping/InspectionMapping.cs
- Survi.Prevention.Models/DataTransfertObjects/InspectionBuildingDetailForWeb.cs
- Survi.Prevention.Models/DataTransfertObjects/InspectionQuestionForList.cs
- Survi.Prevention.Models/DataTransfertObjects/SurveyQuestionChoiceForList.cs
- Survi.Prevention.Models/InspectionManagement/Inspection.cs
- Survi.Prevention.Models/InspectionManagement/InspectionQuestion.cs
- Survi.Prevention.ServiceLayer/Services/InspectionDetailService.cs
- Survi.Prevention.ServiceLayer/Services/InspectionQuestionService.cs
- Survi.Prevention.ServiceLayer/Survi.Prevention.ServiceLayer.csproj
- Survi.Prevention.WebApi/Controllers/InspectionQuestionController.cs
- Survi.Prevention.WebApi/Startup.cs
- Lister les questions pour une inspection ciblée
- Sauvegarder les réponses du questionnaire
- Lister les question et réponses déjà sauvegarder d'une inspection
- Compléter un questionnaire
> #24 mobile management survey

- Survi.Prevention.ServiceLayer/Services/HazardousMaterialService.cs
- Survi.Prevention.ServiceLayer/Services/LaneService.cs
- Survi.Prevention.WebApi/Controllers/HazardousMaterialController.cs
- Survi.Prevention.WebApi/Controllers/LaneController.cs
Lane and hazardous materials :
Add null and empty validation on searchTerm parameter
Limit query to 30 rows max
Add validation on case sensitive
Add order by on name
> #11 optimize search

- Survi.Prevention.ServiceLayer/Services/InspectionBuildingAnomalyPictureService.cs
- Survi.Prevention.ServiceLayer/Services/InspectionBuildingAnomalyService.cs
- Survi.Prevention.WebApi/Controllers/InspectionBuildingAnomalyController.cs
remove pictures when removing anomaly pictures and both when removing anomaly
> feat(#47) : Manage removal of anomaly pictures

- Survi.Prevention.ServiceLayer/Services/BuildingService.cs
- Survi.Prevention.ServiceLayer/Services/HazardousMaterialService.cs
- Survi.Prevention.ServiceLayer/Services/LaneService.cs
- Survi.Prevention.ServiceLayer/Services/PersonRequiringAssistanceTypeService.cs
- Survi.Prevention.ServiceLayer/Services/RiskLevelService.cs
- Survi.Prevention.ServiceLayer/Services/UtilisationCodeService.cs
- Survi.Prevention.WebApi/Controllers/BuildingController.cs
- Survi.Prevention.WebApi/Controllers/HazardousMaterialController.cs
- Survi.Prevention.WebApi/Controllers/LaneController.cs
- Survi.Prevention.WebApi/Controllers/PersonRequiringAssistanceTypeController.cs
- Survi.Prevention.WebApi/Controllers/RiskLevelController.cs
- Survi.Prevention.WebApi/Controllers/UtilisationCodeController.cs
Faire le pull request #70 avant celui-ci
> #78 building child

- Survi.Prevention.ServiceLayer/Services/BuildingContactService.cs
- Survi.Prevention.ServiceLayer/Services/BuildingService.cs
- Survi.Prevention.ServiceLayer/Services/HazardousMaterialService.cs
- Survi.Prevention.ServiceLayer/Services/LaneService.cs
- Survi.Prevention.ServiceLayer/Services/PersonRequiringAssistanceTypeService.cs
- Survi.Prevention.ServiceLayer/Services/RiskLevelService.cs
- Survi.Prevention.ServiceLayer/Services/UtilisationCodeService.cs
- Survi.Prevention.WebApi/Controllers/BuildingContactController.cs
- Survi.Prevention.WebApi/Controllers/BuildingController.cs
- Survi.Prevention.WebApi/Controllers/HazardousMaterialController.cs
- Survi.Prevention.WebApi/Controllers/LaneController.cs
- Survi.Prevention.WebApi/Controllers/PersonRequiringAssistanceTypeController.cs
- Survi.Prevention.WebApi/Controllers/RiskLevelController.cs
- Survi.Prevention.WebApi/Controllers/UtilisationCodeController.cs
- Survi.Prevention.WebApi/Startup.cs
Faire le pull request #71 avant celui-ci
> #80 building contact

- Survi.Prevention.ServiceLayer/Services/BuildingContactService.cs
- Survi.Prevention.ServiceLayer/Services/BuildingPersonRequiringAssistanceService.cs
- Survi.Prevention.WebApi/Controllers/BuildingContactController.cs
- Survi.Prevention.WebApi/Controllers/BuildingPersonsRequiringAssistanceController.cs
- Survi.Prevention.WebApi/Startup.cs
Faire le pull request #73 avant celui-ci
> #79 building pnaps

- Survi.Prevention.ServiceLayer/Services/BuildingHazardousMaterialService.cs
- Survi.Prevention.ServiceLayer/Services/BuildingPersonRequiringAssistanceService.cs
- Survi.Prevention.ServiceLayer/Services/HazardousMaterialService.cs
- Survi.Prevention.WebApi/Controllers/BuildingHazardousMaterialController.cs
- Survi.Prevention.WebApi/Controllers/BuildingPersonsRequiringAssistanceController.cs
- Survi.Prevention.WebApi/Controllers/HazardousMaterialController.cs
- Survi.Prevention.WebApi/Startup.cs
Faire le pull request #74 avant celui-ci
> #81 building hazardous material

- Survi.Prevention.DataLayer/Mapping/PictureMapping.cs
- Survi.Prevention.Models/DataTransfertObjects/PictureForWeb.cs
- Survi.Prevention.Models/Picture.cs
- Survi.Prevention.ServiceLayer/Services/PictureService.cs
Saving and loading JSON for the edited image.
> #79 sketch-integration

- Survi.Prevention.ServiceLayer/Services/PictureService.cs
Ajout de l'enregistrement du sketch
> fix(#89): Missing sketch saving

- Survi.Prevention.ServiceLayer/Localization/Base/EnumItem.cs
- Survi.Prevention.ServiceLayer/Localization/EnumResource.Designer.cs
- Survi.Prevention.ServiceLayer/Localization/EnumResource.en.resx
- Survi.Prevention.ServiceLayer/Localization/EnumResource.resx
Add translation to getname function of direction enum
- Add resources translation for english
> feat(#101) Add translation in webapi

- Survi.Prevention.DataLayer/ManagementContext.cs
- Survi.Prevention.DataLayer/Scripts/views.sql
- Survi.Prevention.DataLayer/Survi.Prevention.DataLayer.csproj
- Survi.Prevention.Models/DataTransfertObjects/InspectionForDashboard.cs
- Survi.Prevention.Models/Survi.Prevention.Models.csproj
- Survi.Prevention.ServiceLayer.Tests/Survi.Prevention.ServiceLayer.Tests.csproj
- Survi.Prevention.ServiceLayer/Services/InspectionService.cs
- Survi.Prevention.ServiceLayer/Services/QueryHelper.cs
- Survi.Prevention.ServiceLayer/Survi.Prevention.ServiceLayer.csproj
- Survi.Prevention.WebApi/Controllers/BuildingForDashboardController.cs
- Survi.Prevention.WebApi/Controllers/InspectionController.cs
- Survi.Prevention.WebApi/Controllers/ReportConfigurationTemplateController.cs
- Survi.Prevention.WebApi/ODataExtensions.cs
- Survi.Prevention.WebApi/Program.cs
- Survi.Prevention.WebApi/Startup.cs
- Survi.Prevention.WebApi/Survi.Prevention.WebApi.csproj
Les 4 modes pour le tableau de bord maintenant en OData:
* http://localhost:5555/api/odata/BuildingsWithoutInspection
* http://localhost:5555/api/odata/InspectionsForApproval
* http://localhost:5555/api/odata/InspectionsToDo
* http://localhost:5555/api/odata/InspectionsCompleted
+ mise à jour des nugets.
> #68 o data

- Survi.Prevention.ServiceLayer/Services/BaseCrudService.cs
- Survi.Prevention.ServiceLayer/Services/BuildingContactService.cs
- Survi.Prevention.ServiceLayer/Services/BuildingHazardousMaterialService.cs
- Survi.Prevention.ServiceLayer/Services/BuildingPersonRequiringAssistanceService.cs
- Survi.Prevention.ServiceLayer/Services/InspectionBuildingAlarmPanelService.cs
- Survi.Prevention.ServiceLayer/Services/InspectionBuildingAnomalyService.cs
- Survi.Prevention.ServiceLayer/Services/InspectionBuildingContactService.cs
- Survi.Prevention.ServiceLayer/Services/InspectionBuildingHazardousMaterialService.cs
- Survi.Prevention.ServiceLayer/Services/InspectionBuildingPersonRequiringAssistanceService.cs
- Survi.Prevention.ServiceLayer/Services/InspectionBuildingSprinklerService.cs
Add generic entity return for method Get(id) and GetList().
> feat(#76) Modify basecrudservice abstract methods to virtual ones

- README.md
- Survi.Prevention.ServiceLayer/Report.cs
- Survi.Prevention.ServiceLayer/ReportPlaceholders.cs
- Survi.Prevention.ServiceLayer/Services/ReportConfigurationTemplateService.cs
- Survi.Prevention.ServiceLayer/Services/ReportGenerationService.cs
- Survi.Prevention.ServiceLayer/Survi.Prevention.ServiceLayer.csproj
- Survi.Prevention.WebApi/Controllers/ReportConfigurationTemplateController.cs
- Survi.Prevention.WebApi/Controllers/ReportGenerationController .cs
- Survi.Prevention.WebApi/Startup.cs
- install-scripts/wkhtmltopdf/ubuntu/install.sh
- install.sh
Generate PDF report from html template.
> #149 report generator

- Survi.Prevention.ServiceLayer/ReportPlaceholders.cs
- Survi.Prevention.ServiceLayer/Services/ReportConfigurationTemplateService.cs
- Survi.Prevention.WebApi/Controllers/ReportConfigurationTemplateController.cs
Obtention de la liste des placeholders.
Il faut une liste sous forme de texte à afficher à l'utilisateur.
> feat(#104): Fetch available placeholders

- Survi.Prevention.ServiceLayer/Services/CityService.cs
- Survi.Prevention.ServiceLayer/Services/InspectionService.cs
- Survi.Prevention.ServiceLayer/Services/WebuserService.cs
- Survi.Prevention.WebApi/Controllers/BuildingForDashboardController.cs
Le filtre s'ajoute automatiquement aux IQueryables utilisés par OData en utilisant le user du token pour aller chercher ses villes.
> #202 add ssi filter to odata queries

- Survi.Prevention.Models/DataTransfertObjects/InspectionBuildingDetailForWeb.cs
- Survi.Prevention.Models/DataTransfertObjects/InspectionConfiguration.cs
- Survi.Prevention.ServiceLayer/Services/InspectionDetailService.cs
Ajoute les champs de la configuration d'inspection (selon ssi + niveau de risque) du bâtiment principal à l'objet retourné par le get de l'InspectionDetail's controller.
> Feat(#25) Add inspection's configuration fields to the inspection detail.

- Survi.Prevention.ServiceLayer/Services/InspectionBuildingAnomalyService.cs
Deactivate pictures of anomaly instead of deleting it
> feat(#96) Deactivate instead of delete picture of anomaly

- Survi.Prevention.ServiceLayer/Services/InspectionBuildingAnomalyPictureService.cs
- Survi.Prevention.ServiceLayer/Services/InspectionBuildingParticularRiskPictureService.cs
- Survi.Prevention.ServiceLayer/Services/PictureService.cs
- Survi.Prevention.WebApi/Controllers/InspectionBuildingAnomalyPictureController.cs
- Survi.Prevention.WebApi/Controllers/InspectionBuildingParticularRiskPictureController.cs
- Survi.Prevention.WebApi/Controllers/PictureController.cs
Validation on picture saving method(mimetype)
Remove unused saving pictures methods
> #96 validate anomaly save

- Survi.Prevention.ServiceLayer/Localization/EnumResource.Designer.cs
- Survi.Prevention.ServiceLayer/Localization/EnumResource.en.resx
- Survi.Prevention.ServiceLayer/Localization/EnumResource.resx
- Survi.Prevention.ServiceLayer/LocalizedResourceGenerator.cs
- Survi.Prevention.ServiceLayer/Services/InspectionBuildingAlarmPanelService.cs
- Survi.Prevention.ServiceLayer/Services/InspectionBuildingAnomalyPictureService.cs
- Survi.Prevention.ServiceLayer/Services/InspectionBuildingParticularRiskPictureService.cs
- Survi.Prevention.ServiceLayer/Services/InspectionBuildingSprinklerService.cs
- Survi.Prevention.ServiceLayer/Services/PictureService.cs
- Survi.Prevention.WebApi/Controllers/InspectionBuildingAnomalyPictureController.cs
- Survi.Prevention.WebApi/Controllers/InspectionBuildingParticularRiskPictureController.cs
- Survi.Prevention.WebApi/Controllers/PictureController.cs
Add translation to fire protection list from API
> #128 translation errors validation

- Survi.Prevention.ServiceLayer/Services/InspectionService.cs
- Survi.Prevention.WebApi/Controllers/InspectionController.cs
Create function to check if user can access target inspection
> #132 inspection user access

- Survi.Prevention.Models/DataTransfertObjects/InspectionPictureForWeb.cs
- Survi.Prevention.ServiceLayer/Reporting/ReportBuildingAnomalyPictureGroupHandler.cs
- Survi.Prevention.ServiceLayer/Reporting/ReportBuildingParticularRiskPictureGroupHandler.cs
- Survi.Prevention.ServiceLayer/Services/BuildingAnomalyService.cs
- Survi.Prevention.ServiceLayer/Services/BuildingDetailService.cs
- Survi.Prevention.ServiceLayer/Services/BuildingParticularRiskService.cs
- Survi.Prevention.ServiceLayer/Services/InspectionBuildingAnomalyPictureService.cs
- Survi.Prevention.ServiceLayer/Services/InspectionBuildingParticularRiskPictureService.cs
- Survi.Prevention.ServiceLayer/Services/InspectionPictureService.cs
- Survi.Prevention.WebApi/Controllers/InspectionBuildingAnomalyPictureController.cs
- Survi.Prevention.WebApi/Controllers/InspectionBuildingParticularRiskPictureController.cs
- Survi.Prevention.WebApi/Controllers/InspectionPictureController.cs
Use one model to manage picture for web
> #154 refactor picture component

- Survi.Prevention.WebApi/Controllers/HazardousMaterialController.cs
- Survi.Prevention.WebApi/Controllers/LaneController.cs
Attention aussi un pull request dans mobile.
> #230 hazardous materials slash in search term

- Survi.Prevention.ServiceLayer/Services/AuthentificationService.cs
Attention, va avec un pull request dans SURVIP.
> #365 refresh token not working correctly anymore

- Survi.Prevention.ServiceLayer/Services/InspectionBatchService.cs
> Fix(#359) Add missing includes in the get(id) call.

- Survi.Prevention.ServiceLayer/DataCopy/ReportTemplateDuplicator.cs
- Survi.Prevention.ServiceLayer/Services/ReportConfigurationTemplateService.cs
- Survi.Prevention.WebApi/Controllers/ReportConfigurationTemplateController.cs
Permet la duplication d'un template de rapport
> feat(#248) Add report template duplication

- Survi.Prevention.Models/DataTransfertObjects/UnitOfMeasureForDisplay.cs
- Survi.Prevention.Models/Survi.Prevention.Models.csproj
- Survi.Prevention.Models/UnitOfMeasure.cs
- Survi.Prevention.ServiceLayer/Services/UnitOfMeasureService.cs
- Survi.Prevention.WebApi/Controllers/BaseCrudControllerWithImportation.cs
- Survi.Prevention.WebApi/Controllers/UnitOfMeasureController.cs
Nécessaire pour le pull request 297 de survip-mobile
> Feat(#297) Add a way to get all unit of measures at once.

- Survi.Prevention.ServiceLayer/Services/FirestationService.cs
- Survi.Prevention.WebApi/Controllers/FirestationController.cs
Permet de renvoyer les seulement les firestations du ssi de l'utilisateur.
> #435 unauthorized firestations

- Survi.Prevention.DataLayer/Mapping/ReportConfigurationTemplateMapping.cs
- Survi.Prevention.DataLayer/Migrations/20190121023721_Issue257-AddReportByFireStation.Designer.cs
- Survi.Prevention.DataLayer/Migrations/20190121023721_Issue257-AddReportByFireStation.cs
- Survi.Prevention.Models/ReportConfigurationTemplate.cs
- Survi.Prevention.ServiceLayer/DataCopy/ReportTemplateDuplicator.cs
- Survi.Prevention.ServiceLayer/Services/ReportConfigurationTemplateService.cs
- Survi.Prevention.WebApi/Controllers/ReportConfigurationTemplateController.cs
Ajoute un idFireSafetyDepartment au rapport
Ajoute un IsDefault
Retourne que les rapports qui sont reliés aux SSIs auxquels l'usager à accès
> #257 report ssi

- Survi.Prevention.ServiceLayer/DataCopy/InspectionBuildingDataCopyDeleter.cs
- Survi.Prevention.ServiceLayer/Reporting/PictureHtmlTagGenerator.cs
- Survi.Prevention.ServiceLayer/Reporting/ReportBuildingAnomalyPictureGroupHandler.cs
- Survi.Prevention.ServiceLayer/Reporting/ReportBuildingParticularRiskPictureGroupHandler.cs
- Survi.Prevention.ServiceLayer/Reporting/ReportBuildingPersonRequiringAssistanceGroupHandler.cs
- Survi.Prevention.ServiceLayer/Reporting/ReportBuildingSprinklerGroupHandler.cs
- Survi.Prevention.ServiceLayer/Reporting/ReportInspectionGroupHandler.cs
- Survi.Prevention.ServiceLayer/Reporting/ReportMainBuildingGroupHandler.cs
- Survi.Prevention.ServiceLayer/Services/BuildingParticularRiskService.cs
- Survi.Prevention.ServiceLayer/Services/BuildingService.cs
- Survi.Prevention.ServiceLayer/Services/FireSafetyDepartmentService.cs
- Survi.Prevention.ServiceLayer/Services/InspectionService.cs
- Survi.Prevention.ServiceLayer/Services/ReportConfigurationTemplateService.cs
Testeur: voir les commentaires dans le point #264 svp.
Ce point règle deux autres issues en plus de #264.
> #264 add firesafety logo to report configurator

- Survi.Prevention.ServiceLayer/Services/InspectionBuildingService.cs
> Fix(#332) Building that have not been inspected should not be returned by the API.
